# Generated by Django 4.0.1 on 2022-02-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'creator',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=256)),
                ('video_clip', models.URLField(max_length=256)),
                ('age_limit_logo', models.CharField(default='', max_length=256)),
                ('star_point', models.CharField(max_length=256)),
                ('total_like', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('actors', models.ManyToManyField(related_name='actor', to='main.Actor')),
                ('creators', models.ManyToManyField(related_name='creator', to='main.Creator')),
                ('genre', models.ManyToManyField(related_name='genre', to='main.Genre')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_description', models.CharField(max_length=10000)),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'db_table': 'video_modal',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs', models.BooleanField(null=True)),
                ('my_list_or_not', models.BooleanField(null=True)),
                ('streaming_info', models.CharField(default='0s', max_length=256)),
                ('star_info', models.CharField(default='0', max_length=256)),
                ('profile_id', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='user.profileid')),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
    ]
